version: '3.8'

services:
  app:
    image: ngominhthanh852/dockerforuni:0.0.1
    ports:
      - 8080:8080
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: university
      MYSQL_PASSWORD: Thanh@123
      MYSQL_ROOT_PASSWORD: Thanh@123
